package vistas;

import dao.AsistenciaDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Vergara Lopez <your.name at your.org>
 */
public class AsistenciaFrm extends javax.swing.JPanel {

    // Variables globales
    boolean esEditar = false;
    modelo.Asistencia edicionAsistencia;

    /**
     * Creates new form Inicio
     */
    public AsistenciaFrm() {
        initComponents();
        iniciarEstilos();
    }

    // Constructor para editar
    public AsistenciaFrm(modelo.Asistencia asistencia) {
        initComponents();
        esEditar = true;
        edicionAsistencia = asistencia;
        iniciarEstilos();
    }

    private void iniciarEstilos() {
        titulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        titulo.setForeground(Color.BLACK);
        txtIdUsuario.putClientProperty("JTextField.placeholderText", "Ingrese su ID de usuario.");
        cmbTipoAsistencia.putClientProperty("JTextField.placeholderText", "Ingrese el tipo de asistencia.");

        if (esEditar) {
            titulo.setText("Editar Asistencia");
            btnRegistrarAsistencia.setText("Guardar Cambios");

            if (edicionAsistencia != null) {
                // Se muestra el ID del usuario en lugar del ID del registro
                txtIdUsuario.setText(String.valueOf(edicionAsistencia.getUsuarioId()));
            }
        }
    }

    // Código de interfaz
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarAsistencia = new javax.swing.JButton();
        cmbTipoAsistencia = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 410));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("ASISTENCIAS");

        jLabel1.setText("ID USUARIO:");

        jLabel2.setText("TIPO ASISTENCIA:");

        btnRegistrarAsistencia.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarAsistencia.setText("REGISTRAR ASISTENCIA");
        btnRegistrarAsistencia.setBorderPainted(false);
        btnRegistrarAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAsistenciaActionPerformed(evt);
            }
        });

        cmbTipoAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA", "SALIDA" }));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoAsistencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnRegistrarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnRegistrarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAsistenciaActionPerformed
        // Obtener la fecha y hora actuales
        java.sql.Date fechaActual = new java.sql.Date(System.currentTimeMillis());
        java.sql.Time horaActual = new java.sql.Time(System.currentTimeMillis());
        
        // Capturar datos de la interfaz
        int idUsuario = Integer.parseInt(txtIdUsuario.getText());
        String tipoAsistencia = (String) cmbTipoAsistencia.getSelectedItem();

        // Validar campos
        if (idUsuario < 0 || tipoAsistencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
            txtIdUsuario.requestFocus();
            return;
        }

        // Crear la asistencia usando el constructor completo
        modelo.Asistencia asistencia = esEditar 
            ? edicionAsistencia 
            : new modelo.Asistencia(
                  fechaActual, 
                  horaActual, 
                  tipoAsistencia.toLowerCase(), 
                  idUsuario
              );

        try {
            AsistenciaDAO dao = new AsistenciaDAO();
            if (!esEditar) {
                dao.insertarAsistencia(asistencia);
                limpiarCampos();
            } else {
                // Aquí se implementaría la actualización si se requiere
            }
            
            String mensajeExito = esEditar ? "modificada" : "registrada";
            JOptionPane.showMessageDialog(this, "Asistencia " + mensajeExito + " correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);          
        } catch (Exception e) {
            String mensajeError = esEditar ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(this, "Error al " + mensajeError + " asistencia", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrarAsistencia;
    private javax.swing.JComboBox<String> cmbTipoAsistencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables

    // Método para limpiar campos de texto
    private void limpiarCampos() {
        txtIdUsuario.setText("");
        cmbTipoAsistencia.setSelectedIndex(0);
    }
}
