package vistas;

import dao.DAOEstudiantesImpl;
import interfaces.DAOEstudiantes;
import java.awt.Color;
import javax.swing.JOptionPane;
//import modelos.EstudiantesModelo;

/**
 *
 * @author Erick Vergara Lopez <your.name at your.org>
 */
public class EstudiantesFrm extends javax.swing.JPanel {

    // Variables globales
    boolean esEditar = false;
    modelo.EstudiantesModelo edicionEstudiante;

    /**
     * Creates new form Inicio
     */
    public EstudiantesFrm() {
        initComponents();
        iniciarEstilos();
    }

    // Constructor para editar
    public EstudiantesFrm(modelo.EstudiantesModelo estudiante) {
        initComponents();
        esEditar = true;
        edicionEstudiante = estudiante;
        iniciarEstilos();
    }

    private void iniciarEstilos() {
        // Colocar el estilo de letra
        titulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        // Cambiar el color de la letra
        titulo.setForeground(Color.BLACK);
        txtNombre.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del estudiante.");
        txtCarrera.putClientProperty("JTextField.placeholderText", "Ingrese la carrera del estudiante.");
        txtSemestre.putClientProperty("JTextField.placeholderText", "Ingrese el semestre del estudiante (1 - 6).");

        if (esEditar) {
            titulo.setText("Editar Estudiante");
            btnRegistrarEstudiante.setText("Guardar Cambios");

            if (edicionEstudiante != null) {
                txtNombre.setText(edicionEstudiante.getNombre());
                txtCarrera.setText(edicionEstudiante.getCarrera());
                txtSemestre.setText(Integer.toString(edicionEstudiante.getSemestre()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarEstudiante = new javax.swing.JButton();
        txtCarrera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 410));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Registrar Nuevo Estudiante");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRE:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CARRERA:");

        btnRegistrarEstudiante.setText("REGISTRAR ESTUDIANTE");
        btnRegistrarEstudiante.setBorderPainted(false);
        btnRegistrarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstudianteActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SEMESTRE:");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnRegistrarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(btnRegistrarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstudianteActionPerformed
        // Variables para capturar los textFields
        String nombre = txtNombre.getText();
        String carrera = txtCarrera.getText();
        String semestreText = txtSemestre.getText();

        // Validar campos
        if (nombre.isEmpty() || carrera.isEmpty() || semestreText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return; // Detener la ejecución si hay campos vacíos
        }

        // Convertir el semestre a int
        int semestre = 0;
        try {
            semestre = Integer.parseInt(semestreText);
            // Validar semestre ingresado
            if (semestre <= 0 || semestre > 6) {
                JOptionPane.showMessageDialog(this, "Sólo se admite semestre del 1 al 6", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si el semestre no es un número válido
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor del semestre debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si el semestre no es un número válido
        }

        // Instanciar objeto de la clase Estudiantes
        modelo.EstudiantesModelo estudiante = esEditar ? edicionEstudiante : new modelo.EstudiantesModelo();
        estudiante.setNombre(nombre);
        estudiante.setCarrera(carrera);
        estudiante.setSemestre(semestre);

        // En el try-catch instanciamos un objeto de la interfaz e implmentacion de DAOEstudiantes
        try {
            DAOEstudiantes dao = new DAOEstudiantesImpl();
            if (!esEditar) {
                dao.registrar(estudiante);
                limpiarCampos();
            } else {
                dao.editar(estudiante);
            }
            
            // Variable de mensajes
            String mensajeExito = esEditar ? "modificado" : "registrado";
            JOptionPane.showMessageDialog(this, "Estudiante " + mensajeExito + " correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);          
        } catch (Exception e) {
            String mensajeError = esEditar ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(this, "Error al " + mensajeError + " estudiante", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrarEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables

    // Método para limpiar campos de texto
    private void limpiarCampos() {
        txtNombre.setText("");
        txtCarrera.setText("");
        txtSemestre.setText("");
    }
}
