package vistas;

import dao.DAOEstudiantesImpl;
import dao.DAORegistroAccesoImpl;
import dao.DAOTrabajadoresImpl;
import interfaces.DAOEstudiantes;
import interfaces.DAORegistroAcceso;
import interfaces.DAOTrabajadores;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import modelo.EstudiantesModelo;
import modelo.RegistroAccesoModelo;
import modelo.TrabajadoresModelo;

/**
 *
 * @author Erick Vergara Lopez <your.name at your.org>
 */
public class IngresosFrm extends javax.swing.JPanel {

    
    // Variables globales
    boolean esEstudiante = false;
    /**
     * Creates new form Inicio
     */
    public IngresosFrm() {
        initComponents();
        iniciarEstilos();
    }
    
    private void iniciarEstilos() {
        // Colocar el estilo de letra
        titulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        // Cambiar el color de la letra
        titulo.setForeground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMarcarIngreso = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 410));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Registrar Nuevo Ingreso");

        jLabel1.setText("ID:");

        jLabel2.setText("NOMBRE:");

        btnMarcarIngreso.setText("MARCAR INGRESO");
        btnMarcarIngreso.setBorderPainted(false);
        btnMarcarIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarcarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(208, 208, 208))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnMarcarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(82, 82, 82)
                .addComponent(btnMarcarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(197, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(166, 166, 166)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarIngresoActionPerformed
        // Variables para capturar los campos
        String idPersona = txtId.getText();
        String nombrePersona = txtNombre.getText();
        
        // Validar campos
        if (idPersona.isEmpty() || nombrePersona.isEmpty()) {
            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            // Establecer el foco
            txtId.requestFocus();
            return; // Detener la ejecución
        } else if (!esNumerico(idPersona)) {
            JOptionPane.showMessageDialog(this, "El campo ID debe ser un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocus();
            return;
        } else if (Integer.parseInt(idPersona) <= 0) {
            JOptionPane.showMessageDialog(this, "El campo ID debe ser un número mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocus();
            return;
        }
        
        
        try {
            // Validar lógicas de negocio
            
            // Validar si existe el estudiante
            DAOEstudiantes daoEstudiantes = new DAOEstudiantesImpl();
            EstudiantesModelo estudianteActual = daoEstudiantes.getEstudianteById(Integer.parseInt(idPersona));
            if (estudianteActual == null) {
                JOptionPane.showMessageDialog(this, "No existe un estudiante con ese ID y nombre", "Error", JOptionPane.ERROR_MESSAGE);
                txtId.requestFocus();
                return;
            } 
            
            // Validar si existe un trabajador
            DAOTrabajadores daoTrabajadores = new DAOTrabajadoresImpl();
            TrabajadoresModelo trabajadorActual = daoTrabajadores.getTrabajadorById(Integer.parseInt(idPersona));
            if (trabajadorActual == null) {
                JOptionPane.showMessageDialog(this, "No existe un trabajador con ese ID y nombre", "Error", JOptionPane.ERROR_MESSAGE);
                txtId.requestFocus();
                return;
            }
            
            // Validar si existe un registro de ingreso de una persona
            DAORegistroAcceso daoRegistros = new DAORegistroAccesoImpl();
            RegistroAccesoModelo registroActual = daoRegistros.getRegistro(estudianteActual, trabajadorActual);
            if (registroActual != null) {
               JOptionPane.showMessageDialog(this, "Esta persona ya registró su ingreso", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            
        // Después de validar, registramos el acceso
        RegistroAccesoModelo registro = new RegistroAccesoModelo();
        int idEstudiante = estudianteActual.getIdEstudiante();
        int idTrabajador = trabajadorActual.getIdTrabajador();
        registro.setIdEstudiante(idEstudiante);
        registro.setIdTrabajador(idTrabajador);
        registro.setNombrePersona(nombrePersona);
        registro.setFechaHoraIngreso(obtenerFechaHoraActual());
        daoRegistros.registrar(registro);
        JOptionPane.showMessageDialog(this, "Ingreso registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        txtId.setText("");
        txtNombre.setText("");
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar el ingreso. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }
       
    }//GEN-LAST:event_btnMarcarIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnMarcarIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean esNumerico(String idPersona) {
        if (idPersona == null) {
            return false;
        }
        try {
            double valorEntero = Integer.parseInt(idPersona);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    // Método para obtener la fecha y hora actual
    public static String obtenerFechaHoraActual() {
        // Obtener la fecha y hora actual
        LocalDateTime fechaHoraActual = LocalDateTime.now();
        
        // Formatear la fecha y hora según el formato de la base de datos
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fechaHoraFormateada = fechaHoraActual.format(formatter);
        return fechaHoraFormateada;
    }
}
