package vistas;

// import dao.DAOEstudiantesImpl;
import dao.Dashboard;
// import interfaces.DAOEstudiantes;
import dao.AsistenciaDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick Vergara Lopez <your.name at your.org>
 */
public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form EstudiantesFrm
     */
    public Reportes() {
        initComponents();
        iniciarEstilos();
        // cargarEstudiantes();
        cargarAsistencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencias = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("Estudiantes");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tablaAsistencias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fecha", "hora", "tipo", "usuario_id"
            }
        ));
        jScrollPane1.setViewportView(tablaAsistencias);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(324, 324, 324))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Dashboard.mostrarJPanel(new AsistenciaFrm());
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Instancia de DAOEstudiantes
        // DAOEstudiantes dao = new DAOEstudiantesImpl();
        AsistenciaDAO dao = new AsistenciaDAO();
        // Establecer un DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) tablaAsistencias.getModel();
        if (tablaAsistencias.getSelectedRows().length < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar 1 o más estudiantes a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i : tablaAsistencias.getSelectedRows()) {
                try {
                    // Llamamos al metodo eliminar y pasamos como parametro el id de la fila de seleccionada de la tabla
                    dao.eliminarAsistencia((int) tablaAsistencias.getValueAt(i, 0));
                    // Eliminar fila del modelo
                    modelo.removeRow(i);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tablaAsistencias.getSelectedRow() > -1) {
            try {
                // Obtener el idEstudiante
                int idUsuario = (int) tablaAsistencias.getValueAt(tablaAsistencias.getSelectedRow(), 0);
                // DAOEstudiantes dao = new DAOEstudiantesImpl();
                AsistenciaDAO dao = new AsistenciaDAO();
                Dashboard.mostrarJPanel(new AsistenciaFrm(dao.obtenerAsistenciaPorId(idUsuario)));
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el estudiante a editar", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Valor de textField de buscar
            String usuarioBuscar = txtBuscar.getText();
            // Instancia de DAOEstudiantes         
            // DAOEstudiantes dao = new DAOEstudiantesImpl();
            AsistenciaDAO dao = new AsistenciaDAO();
            // Establecer un DefaultTableModel
            DefaultTableModel modelo = (DefaultTableModel) tablaAsistencias.getModel();
            // Limpiar
            modelo.setRowCount(0);
            // Agregar la fila al modelo por cada registro que tenga la tabla estudiante
            dao.listar(usuarioBuscar).forEach((asistencia) -> modelo.addRow(new Object[]{
                asistencia.getId(),
                asistencia.getFecha(),
                asistencia.getHora(),
                asistencia.getTipo(),
                asistencia.getUsuarioId()
            }));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsistencias;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void iniciarEstilos() {
        titulo.putClientProperty("FlatLaf.styleClass", "h1");
        titulo.setForeground(Color.BLACK);
        txtBuscar.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del estudiante a buscar.");
    }

    // Cargar lista de estudiantes
//    private void cargarEstudiantes() {
//        try {
//            DAOEstudiantes dao = new DAOEstudiantesImpl();
//            // Establecer un DefaultTableModel
//            DefaultTableModel modelo = (DefaultTableModel) tablaAsistencias.getModel();
//            // Agregar la fila al modelo por cada registro que tenga la tabla estudiante
//            dao.listar("").forEach((estudiante) -> modelo.addRow(new Object[]{
//                estudiante.getIdEstudiante(),
//                estudiante.getNombre(),
//                estudiante.getCarrera(),
//                estudiante.getSemestre()
//            }));
//        } catch (Exception ex) {
//            System.out.println(ex.getMessage());
//        }
//    }
    
    private void cargarAsistencias() {
        try {
            AsistenciaDAO dao = new AsistenciaDAO();
            DefaultTableModel modelo = (DefaultTableModel) tablaAsistencias.getModel();
            dao.listar("").forEach((asistencia) -> modelo.addRow(new Object[]{
                asistencia.getId(),
                asistencia.getFecha(),
                asistencia.getHora(),
                asistencia.getTipo(),
                asistencia.getUsuarioId()
            }));
        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}
