package vistas;

import dao.DAOTrabajadoresImpl;
import interfaces.DAOTrabajadores;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.TrabajadoresModelo;

/**
 *
 * @author Erick Vergara Lopez <your.name at your.org>
 */
public class TrabajadoresFrm extends javax.swing.JPanel {

    // Variables globales
    boolean esEditar = false;
    TrabajadoresModelo edicionTrabajador;
    
    /**
     * Creates new form Inicio
     */
    public TrabajadoresFrm() {
        initComponents();
        iniciarEstilos();
    }
    
    // Constructor para editar
    public TrabajadoresFrm(TrabajadoresModelo trabajador) {
        initComponents();
        esEditar = true;
        edicionTrabajador = trabajador;
        iniciarEstilos();
    }
    
    private void iniciarEstilos() {
        // Colocar el estilo de letra
        titulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        // Cambiar el color de la letra
        titulo.setForeground(Color.BLACK);
        txtNombre.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del trabajador.");
        txtOcupacion.putClientProperty("JTextField.placeholderText", "Ingrese la ocupación del trabajador.");
        
        if (esEditar) {
            titulo.setText("Editar Estudiante");
            btnRegistrarTrabajador.setText("Guardar Cambios");

            if (edicionTrabajador != null) {
                txtNombre.setText(edicionTrabajador.getNombre());
                txtOcupacion.setText(edicionTrabajador.getOcupacion());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarTrabajador = new javax.swing.JButton();
        txtOcupacion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 410));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Registrar Nuevo Trabajador");

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("OCUPACIÓN:");

        btnRegistrarTrabajador.setText("REGISTRAR TRABAJADOR");
        btnRegistrarTrabajador.setBorderPainted(false);
        btnRegistrarTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(208, 208, 208))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnRegistrarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addGap(81, 81, 81)
                .addComponent(btnRegistrarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(197, Short.MAX_VALUE)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(166, 166, 166)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrabajadorActionPerformed
        // Variables para capturar los textFields
        String nombre = txtNombre.getText();
        String ocupacion = txtOcupacion.getText();
        
        // Validar campos
        if (nombre.isEmpty() || ocupacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return; // Detener la ejecución si hay campos vacíos
        }
        
        // Instanciar modelo de Trabajadores
        TrabajadoresModelo trabajador = esEditar ? edicionTrabajador: new TrabajadoresModelo();
        trabajador.setNombre(nombre);
        trabajador.setOcupacion(ocupacion);
        
        // En el try-catch instanciamos un objeto de la interfaz e implmentacion de DAOEstudiantes
        try {
            DAOTrabajadores dao = new DAOTrabajadoresImpl();
            // Validar editar
            if (!esEditar) {
                dao.registrar(trabajador);
                limpiarCampos();
            } else {
                dao.editar(trabajador);
            }
            
            // Varaible de mensajes
            String mensajeExito = esEditar ? "modificado": "registrado";
            JOptionPane.showMessageDialog(this, "Trabajador " + mensajeExito + " correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
        } catch(Exception ex) {
            String mensajeError = esEditar ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(this, "Error al " + mensajeError + " trabajador.", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarTrabajadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrarTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOcupacion;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtNombre.setText("");
        txtOcupacion.setText("");
    }
}
